name: Generate pacman animation

on:
  schedule:
    - cron: "* */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:  # Permite execução manual do workflow
  push:
    branches:
      - main  # Executa quando houver push na branch 'main'

jobs:
  generate:
    permissions:
      contents: write  # Permissão para escrever no conteúdo do repositório
    runs-on: ubuntu-latest  # Ambiente de execução
    timeout-minutes: 5  # Timeout de 5 minutos

    steps:
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main  # Ação para gerar a animação Pacman
        with:
          github_user_name: ${{ github.repository_owner }}  # Usando o nome do proprietário do repositório

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # Ação para fazer deploy na branch 'output'
        with:
          target_branch: output  # Definindo a branch para o deploy
          build_dir: dist  # Pasta que contém os arquivos gerados pela animação
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token do GitHub para autenticação
