name: Generate Snake Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobra
        uses: Platane/snk@v3
        with:
          github_user_name: "leduardomdias"
          github_token: ${{ secrets.GITHUB_TOKEN }} # Garantir que o token de autenticação está presente

      - name: Commit e Push da animação
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist